### ISSUE TITLE
The Checklist doesnt reset

### ISSUE THREAD

**Issue by FlowFlower123** [kevinhau-to/lostark-account-checklist#2]
Happend 3 times now, i start my PC after reset, open my Webbrowser for the Site and nothing resets.
Have to do it manually alt+ left click.

**Comment by khto-dev** [comment]
Hey @FlowFlower123,

I apologize for the inconvenience! I have heard of the checklist failing to reset if the tab is inactive at time of reset, which i have pushed a fix for, but I have not heard of anyone having problems with the reset from a cold boot. If there's any additional information you can provide, such as time of when you close and open the checklist for the day, I'd be glad to take a look and see if there's anything I can do.

Until then, you could use your browser's developer console (F12 on Google Chrome; Ctrl+Shift+J on Firefox) and input the command `ResetDailyTasks()` as a band-aid solution.

**Comment by FlowFlower123** [comment]
When i close my Browser all my tabs are saved, so when i open my browser the next Day the Site are all there to continue.
But the Daily Stuff didn´t reset.
Gonna look tomorrow when i start my PC and open The Site, if its still the same.
